"""empty message

Revision ID: 074e1721c884
Revises: cd875477bec2
Create Date: 2025-04-14 20:35:14.866211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '074e1721c884'
down_revision = 'cd875477bec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###
